Got madsdk-x86_64-macos working again

diff --git a/profile/madsdk-x86_64-macos/pkg/pkg_post_install b/profile/madsdk-x86_64-macos/pkg/pkg_post_install
--- a/profile/madsdk-x86_64-macos/pkg/pkg_post_install
+++ b/profile/madsdk-x86_64-macos/pkg/pkg_post_install
@@ -11,23 +11,47 @@ os_ver=$(sw_vers -productVersion)
 major=$(echo "$os_ver" | awk -F. '{ print $1; }')
 minor=$(echo "$os_ver" | awk -F. '{ print $2; }')
 
-if [[ $major != 10 ]]; then
-   echo "Invalid OS major version number: $major"
+case $major in
+
+    10)
+
+	case $minor in
+	    10|11|12|13)
+		sysroot='/'
+		;;
+	    14|15)
+		sysroot='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
+		;;
+	    *)
+		echo "Invalid OS minor version number: $minor"
+		exit 1
+		;;
+	esac
+	;;
+
+    11|12)
+
+	sysroot='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
+	;;
+
+    *)
+	
+	echo "Invalid OS major version number: $major"
+	exit 1
+	;;
+
+esac
+
+if [[ ! -e $sysroot ]]; then
+   osascript <<-EndOfScript
+display dialog "Error locating Xcode command-line tools" buttons {"OK"} default button 1 with icon caution with title "Install MAD SDK"
+EndOfScript
    exit 1
 fi
 
-case $minor in
-    10|11|12|13)
-	sysroot='/'
-	;;
-    14|15)
-	sysroot='/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk'
-	;;
-    *)
-	echo "Invalid OS minor version number: $minor"
-	exit 1
-	;;
-esac
+if [[ -L $sysroot ]]; then
+    sysroot=`dirname $sysroot`/`readlink $sysroot`
+fi
 
 rm -f ${MADSDK_ROOT}/sysroot
 ln -s $sysroot ${MADSDK_ROOT}/sysroot
@@ -38,7 +62,9 @@ mkheaders=$(find "$MADSDK_ROOT/" -name mkheaders | head -n 1)
 $mkheaders "$MADSDK_ROOT"
 
 if [ $? != 0 ]; then
-    echo "Error regenerating headers"
+   osascript <<-EndOfScript
+display dialog "Error regenerating compiler headers" buttons {"OK"} default button 1 with icon note caution title "Install MAD SDK"
+EndOfScript
     exit 1
 fi
 
