Big cleanup of files, as part of migration toward new git-based versioning approach

diff --git a/package/init_scripts/init_scripts b/package/init_scripts/init_scripts
--- a/package/init_scripts/init_scripts
+++ b/package/init_scripts/init_scripts
@@ -18,7 +18,7 @@ unpack () {
     rm -rf $SD
     mkdir $SD
 
-    cp ${SDK2_PROFILE_ROOT}/common/init_scripts/preq_check.ac ${SD}/
+    cp ${FD}/preq_check.ac ${SD}/
 
 }
 
@@ -47,20 +47,27 @@ install () {
 
     cd $BD
 
-    cp -av ${PD}/init_scripts/init.sh ${DEST_ROOT}/bin/${PROFILE_NAME}_init.sh
-    cp -av ${PD}/init_scripts/init.csh ${DEST_ROOT}/bin/${PROFILE_NAME}_init.csh
+    files_dir=${FD}/${SDK2_PLATFORM_NAME}/${SDK2_PLATFORM_ISA}
+
+    if [[ ! -d $files_dir ]];
+       echo "Unable to determine which files directory to use"
+       exit 1
+    fi
+
+    cp -av ${files_dir}/init.sh ${DEST_ROOT}/bin/${PROFILE_NAME}_init.sh
+    cp -av ${files_dir}/init.csh ${DEST_ROOT}/bin/${PROFILE_NAME}_init.csh
 
     if [[ $SDK2_PLATFORM_NAME = 'Linux' ]]; then
-        cp -av ${PD}/init_scripts/arch_check ${DEST_ROOT}/bin/${PROFILE_NAME}_arch_check
+        cp -av ${files_dir}/arch_check ${DEST_ROOT}/bin/${PROFILE_NAME}_arch_check
     	cp -av preq_check ${DEST_ROOT}/bin/${PROFILE_NAME}_preq_check
     fi
 
     # Create the version script
 
-    version_string="${PROFILE_ARCH}-${SDK2_RELEASE}"
+    version_string="${PROFILE_ARCH}-${PROFILE_RELEASE}"
 
     sed -e s/@VERSION_STRING@/${version_string}/g \
-	${SDK2_PROFILE_ROOT}/common/init_scripts/version > ${DEST_ROOT}/bin/${PROFILE_NAME}_version
+	${FD}/version > ${DEST_ROOT}/bin/${PROFILE_NAME}_version
     chmod a+x ${DEST_ROOT}/bin/${PROFILE_NAME}_version
 
 }
diff --git a/profile/mesasdk-aarch64-macos/pkg/build_pkg b/profile/mesasdk-aarch64-macos/pkg/build_pkg
--- a/profile/mesasdk-aarch64-macos/pkg/build_pkg
+++ b/profile/mesasdk-aarch64-macos/pkg/build_pkg
@@ -2,6 +2,18 @@
 
 ### VALIDATION ###
 
+# Check SDK2_ROOT is set and valid
+
+if [[ -z $SDK2_ROOT ]]; then
+    echo "Environment variable SDK2_ROOT is not set"
+    exit 1
+fi
+
+if [[ ! -d $SDK2_ROOT ]]; then
+    echo "Root directory '$SDK2_ROOT' is missing"
+    exit 1
+fi
+
 # Check SDK2_TMP is set and valid
 
 if [[ -z $SDK2_TMP ]]; then
@@ -11,13 +23,6 @@ fi
 
 if [[ ! -d $SDK2_TMP ]]; then
     echo "Temporary directory '$SDK2_TMP' is missing"
-    exit 1
-fi
-
-# Check SDK2_RELEASE is set
-
-if [[ -z $SDK2_RELEASE ]]; then
-    echo "Environment variable SDK2_RELEASE is not set"
     exit 1
 fi
 
@@ -39,10 +44,23 @@ fi
 
 # Define standard directories
 
+export SDK2_PACKAGE_ROOT=${SDK2_ROOT}/package
+export SDK2_PROFILE_ROOT=${SDK2_ROOT}/profile
+
 export SDK2_BUILD_ROOT=${SDK2_TMP}/build
+
 export SDK2_PKG_ROOT=${SDK2_TMP}/pkg
 
-export DEST_ROOT=${SDK2_TMP}/mesasdk
+# Include profile settings
+
+export profile_dir=${SDK2_PROFILE_ROOT}/${SDK2_PROFILE}
+
+if [[ ! -d $profile_dir ]]; then
+    echo "Directory '$profile_dir' is missing"
+    exit 1
+fi
+
+. ${profile_dir}/settings
 
 ### ACTION ###
 
@@ -54,7 +72,7 @@ mkdir -p $SDK2_PKG_ROOT
 
 pkgproj_file=$(mktemp ${SDK2_PKG_ROOT}/mesasdk.XXXXXX)
 
-sed -e "s|@RELEASE@|$SDK2_RELEASE|g" \
+sed -e "s|@RELEASE@|$PROFILE_RELEASE|g" \
     -e "s|@PKG_ROOT@|$SDK2_PKG_ROOT|g" \
     -e "s|@DEST_ROOT@|$DEST_ROOT|g" \
     -e "s|@PKG_CERT_NAME@|$SDK2_PKG_CERT_NAME|g" \
