Updated so that work/output files are written into SDK2_TMP

diff --git a/profile/mesasdk-x86_64-macos/pkg/submit_pkg_for_notarization b/profile/mesasdk-x86_64-macos/pkg/submit_pkg_for_notarization
--- a/profile/mesasdk-x86_64-macos/pkg/submit_pkg_for_notarization
+++ b/profile/mesasdk-x86_64-macos/pkg/submit_pkg_for_notarization
@@ -1,5 +1,19 @@
 #!/usr/bin/env bash
 
+### VALIDATION ###
+
+# Check SDK2_TMP is set and valid
+
+if [[ -z $SDK2_TMP ]]; then
+    echo "Environment variable SDK2_TMP is not set"
+    exit 1
+fi
+
+if [[ ! -d $SDK2_TMP ]]; then
+    echo "Temporary directory '$SDK2_TMP' is missing"
+    exit 1
+fi
+
 # Check SDK2_RELEASE is set
 
 if [[ -z $SDK2_RELEASE ]]; then
@@ -14,10 +28,18 @@ if [[ -z $SDK2_NUSER ]]; then
     exit 1
 fi
 
+### VARIABLES ###
+
+# Define standard directories
+
+export SDK2_PKG_ROOT=${SDK2_TMP}/pkg
+
+### ACTION ###
+
 # Submit for notarization
 
 xcrun altool --notarize-app \
              --primary-bundle-id "edu.wisc.astro.pkg.mesasdk" \
              --username "$SDK2_NUSER" \
 	     --password "@keychain:AC_PASSWORD" \
-             --file build/mesasdk-x86_64-macos-$SDK2_RELEASE.pkg
+             --file ${SDK2_PKG_ROOT}/mesasdk-x86_64-macos-$SDK2_RELEASE.pkg
